// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXo6C5l4SSP6aW3dF7NW29_ekqiRDMyKE',
    appId: '1:146598304064:web:889cedbd704de2bf7c42a5',
    messagingSenderId: '146598304064',
    projectId: 'tutorialdb-e02d9',
    authDomain: 'tutorialdb-e02d9.firebaseapp.com',
    storageBucket: 'tutorialdb-e02d9.firebasestorage.app',
    measurementId: 'G-ERJMEX8ZQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAybm0NZQ8p3cEK7NSvufeje66eAmDfbbg',
    appId: '1:146598304064:android:508653f95d4c2c857c42a5',
    messagingSenderId: '146598304064',
    projectId: 'tutorialdb-e02d9',
    storageBucket: 'tutorialdb-e02d9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXo6C5l4SSP6aW3dF7NW29_ekqiRDMyKE',
    appId: '1:146598304064:web:889cedbd704de2bf7c42a5',
    messagingSenderId: '146598304064',
    projectId: 'tutorialdb-e02d9',
    authDomain: 'tutorialdb-e02d9.firebaseapp.com',
    storageBucket: 'tutorialdb-e02d9.firebasestorage.app',
    measurementId: 'G-ERJMEX8ZQ4',
  );
}
